name: Publish FitSMS to npm

on:
  release:
    types: [created]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build_and_test
    runs-on: ubuntu-latest
    # This matches the environment name you set in GitHub Settings
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # Official npm registry
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --access public
        env:
          # Use the secret you created in the previous step
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}